// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_app_task_backend.Data;

namespace movie_app_task_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210912152524_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ActorMedia", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActorsId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("ActorMedia");
                });

            modelBuilder.Entity("movie_app_task_backend.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tom Hiddleston"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brianna Howe"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Carver Wong"
                        },
                        new
                        {
                            Id = 6,
                            Name = "James Hines"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Leon Jarvis"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vinson Moran"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Simpson Evans"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Henry Molina"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mccullough Curry"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Angelia Ruiz"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Hinton Love"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Victoria Alston"
                        });
                });

            modelBuilder.Entity("movie_app_task_backend.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Release_year")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("img_url")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isSeries")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Luke Skywalker attempts to bring his father back to the light side of the Force. At the same time, the rebels hatch a plan to destroy the second Death Star.",
                            Release_year = "1983-05-25",
                            Title = "Star Wars: Return of the Jedi",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZZCMJ4/image?locale=en-us&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "After Princess Leia, the leader of the Rebel Alliance, is held hostage by Darth Vader, Luke and Han Solo must free her and destroy the powerful weapon created by the Galactic Empire.",
                            Release_year = "1977-05-17",
                            Title = "Star Wars: A New Hope",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZXZDZ3/image?locale=en-us&mode=crop&purposes=BoxArt&q=90&h=225&w=150&",
                            isSeries = false
                        },
                        new
                        {
                            Id = 3,
                            Description = "Frodo and Sam arrive in Mordor with the help of Gollum. A number of new allies join their former companions to defend Isengard as Saruman launches an assault from his domain",
                            Release_year = "2002-12-18",
                            Title = "Lord Of The Rings: The Two Towers",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZL60J7/image?locale=en-gb&purposes=BoxArt&mode=scale&q=90&w=162",
                            isSeries = false
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bilbo Baggins, a hobbit, is persuaded into accompanying a wizard and a group of dwarves on a journey to reclaim the city of Erebor and all its riches from the dragon Smaug.",
                            Release_year = "2012-12-13",
                            Title = "The Hobbit: An Unexpected Journey",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZL59HB/image?locale=en-au&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = false
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 6,
                            Description = "The former Fellowship members prepare for the final battle. While Frodo and Sam approach Mount Doom to destroy the One Ring, they follow Gollum, unaware of the path he is leading them to",
                            Release_year = "2013-09-17",
                            Title = "Lord Of The Rings: The Return Of The King",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZL60J7/image?locale=en-gb&purposes=BoxArt&mode=scale&q=90&w=162",
                            isSeries = false
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bilbo Baggins, a hobbit, is persuaded into accompanying a wizard and a group of dwarves on a journey to reclaim the city of Erebor and all its riches from the dragon Smaug.",
                            Release_year = "2013-09-17",
                            Title = "The Hobbit: An Unexpected Journey",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZL59HB/image?locale=en-au&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = false
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bilbo Baggins, a hobbit, and his companions face great dangers on their journey to Laketown. Soon, they reach the Lonely Mountain, where Bilbo comes face-to-face with the fearsome dragon Smaug.",
                            Release_year = "2013-12-12",
                            Title = "The Hobbit: The Desolation of Smaug",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZJ5NLV/image?locale=en-au&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = false
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bilbo fights against a number of enemies to save the life of his Dwarf friends and protects the Lonely Mountain after a conflict arises.",
                            Release_year = "2014-12-11",
                            Title = "The Hobbit: The Battle of the Five Armies",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.movie.8D6KGWZTH3PF/image?locale=en-nz&purposes=BoxArt&mode=scale&q=90&w=162",
                            isSeries = false
                        },
                        new
                        {
                            Id = 10,
                            Description = "After having been missing for nearly 20 years, Rick Sanchez suddenly arrives at daughter Beth's doorstep to move in with her and her family.",
                            Release_year = "2013-09-17",
                            Title = "Rick and Morty",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN85RB/image?locale=en-us&mode=crop&purposes=BoxArt&q=90&h=300&w=200&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 11,
                            Description = "In the wake of a zombie apocalypse, various survivors struggle to stay alive. As they search for safety and evade the undead, they are forced to grapple with rival groups and difficult choices.",
                            Release_year = "2010-10-31",
                            Title = "The Walking Dead",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN90WK/image?locale=en-us&mode=crop&purposes=BoxArt&q=90&h=300&w=200&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 12,
                            Description = "Michael Burnham and her companions in the USS Discovery travel into the far reaches of space to meet new lifeforms and discover new planets.",
                            Release_year = "2017-09-24",
                            Title = "Star Trek: Discovery",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN8KT4/image?locale=en-us&mode=crop&purposes=BoxArt&q=90&h=300&w=200&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 13,
                            Description = "A sixth-generation homesteader and devoted father, John Dutton controls the largest contiguous ranch in the United States. He operates in a corrupt world where politicians are compromised by influential oil and lumber corporations and land grabs make developers billions.",
                            Release_year = "2018-06-20",
                            Title = "Yellowstone",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN6RB1/image?locale=en-us&mode=crop&purposes=BoxArt&q=90&h=300&w=200&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 16,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 18,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 20,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 21,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 22,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 23,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 24,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        },
                        new
                        {
                            Id = 25,
                            Description = "Ray Holt, an eccentric commanding officer, and his diverse and quirky team of odd detectives solve crimes in Brooklyn, New York City.",
                            Release_year = "2013-09-17",
                            Title = "Brooklyn Nine-Nine",
                            img_url = "https://musicimage.xboxlive.com/catalog/video.tvseason.8D6KGWXN91QP/image?locale=de-de&mode=crop&purposes=BoxArt&q=90&h=225&w=150&format=jpg",
                            isSeries = true
                        });
                });

            modelBuilder.Entity("movie_app_task_backend.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rating_value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaId = 1,
                            Rating_value = 4.6f
                        },
                        new
                        {
                            Id = 2,
                            MediaId = 2,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 3,
                            MediaId = 3,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 4,
                            MediaId = 4,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 5,
                            MediaId = 5,
                            Rating_value = 4.6f
                        },
                        new
                        {
                            Id = 6,
                            MediaId = 6,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 7,
                            MediaId = 7,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 8,
                            MediaId = 8,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 9,
                            MediaId = 9,
                            Rating_value = 4.6f
                        },
                        new
                        {
                            Id = 10,
                            MediaId = 10,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 11,
                            MediaId = 11,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 12,
                            MediaId = 12,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 13,
                            MediaId = 13,
                            Rating_value = 4.6f
                        },
                        new
                        {
                            Id = 14,
                            MediaId = 14,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 15,
                            MediaId = 15,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 16,
                            MediaId = 16,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 17,
                            MediaId = 17,
                            Rating_value = 4.6f
                        },
                        new
                        {
                            Id = 18,
                            MediaId = 18,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 19,
                            MediaId = 19,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 20,
                            MediaId = 20,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 21,
                            MediaId = 21,
                            Rating_value = 4.6f
                        },
                        new
                        {
                            Id = 22,
                            MediaId = 22,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 23,
                            MediaId = 23,
                            Rating_value = 4.5f
                        },
                        new
                        {
                            Id = 24,
                            MediaId = 24,
                            Rating_value = 4.5f
                        });
                });

            modelBuilder.Entity("ActorMedia", b =>
                {
                    b.HasOne("movie_app_task_backend.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_app_task_backend.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_app_task_backend.Models.Rating", b =>
                {
                    b.HasOne("movie_app_task_backend.Models.Media", null)
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_app_task_backend.Models.Media", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
